# Generated by Django 3.2.6 on 2021-11-22 14:55

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modelzoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(null=True, upload_to='static/uploads/modelzoo/%Y-%d-%d/', verbose_name='附件')),
            ],
            options={
                'verbose_name': '附件信息',
                'verbose_name_plural': '附件信息',
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('type', models.CharField(blank=True, choices=[('0', 'Modelzoo-Infer'), ('1', 'Modelzoo-Train'), ('2', 'Daily-Infer'), ('3', 'Daily-Train')], default='0', max_length=5, null=True, verbose_name='类别')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='标题')),
                ('detail', models.TextField(null=True, verbose_name='详细描述')),
                ('user', models.CharField(max_length=20, null=True, verbose_name='创建者')),
                ('version', models.CharField(max_length=50, null=True, verbose_name='版本')),
                ('other', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='其他信息')),
            ],
            options={
                'verbose_name': '报告信息',
                'verbose_name_plural': '报告信息',
            },
        ),
        migrations.DeleteModel(
            name='DailyReportModel',
        ),
        migrations.DeleteModel(
            name='ModelZooModel',
        ),
        migrations.AlterModelOptions(
            name='releasemodel',
            options={'verbose_name': '版本发布', 'verbose_name_plural': '版本发布'},
        ),
        migrations.AddField(
            model_name='releasemodel',
            name='dept',
            field=models.CharField(blank=True, choices=[('0', 'CSE'), ('1', 'QA')], default='0', max_length=5, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='releasemodel',
            name='note',
            field=models.TextField(null=True, verbose_name='发布信息'),
        ),
        migrations.AddField(
            model_name='releasemodel',
            name='other',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='其他信息'),
        ),
        migrations.AddField(
            model_name='releasemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Infer'), ('1', 'Train')], default='0', max_length=5, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='releasemodel',
            name='url',
            field=models.URLField(null=True, verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='releasemodel',
            name='version',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='modelzoo.reportmodel'),
        ),
    ]
