# Generated by Django 3.2.6 on 2021-11-07 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='板卡编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='序列号')),
                ('card_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('card_project', models.CharField(blank=True, max_length=20, null=True, verbose_name='项目名')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('memory', models.CharField(max_length=100, verbose_name='显存')),
                ('power', models.CharField(max_length=50, verbose_name='功耗')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('owner', models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '板卡信息',
                'verbose_name_plural': '板卡信息',
            },
        ),
    ]
