# Generated by Django 3.2.6 on 2021-12-01 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_auto_20211120_1453'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_cardmodel_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCardModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='板卡编号')),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(blank=True, editable=False, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('sn', models.CharField(db_index=True, max_length=50, verbose_name='序列号')),
                ('card_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('card_project', models.CharField(blank=True, max_length=20, null=True, verbose_name='项目名')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('memory', models.CharField(max_length=100, verbose_name='显存')),
                ('power', models.CharField(max_length=50, verbose_name='功耗')),
                ('owner', models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 板卡信息',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
