# Generated by Django 3.2.6 on 2021-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_historicalcardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='status',
            field=models.CharField(choices=[('1', '可借'), ('2', '借出')], default='1', max_length=5, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='historicalcardmodel',
            name='status',
            field=models.CharField(choices=[('1', '可借'), ('2', '借出')], default='1', max_length=5, verbose_name='设备状态'),
        ),
    ]
