# Generated by Django 3.2.6 on 2023-01-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_worknotes'),
        ('cards', '0005_cardborrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='current_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='users.deviceuser', verbose_name='当前使用者'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='pn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='产品号'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='historicalcardmodel',
            name='current_user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.deviceuser', verbose_name='当前使用者'),
        ),
        migrations.AddField(
            model_name='historicalcardmodel',
            name='pn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='产品号'),
        ),
        migrations.AddField(
            model_name='historicalcardmodel',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用途分类'),
        ),
        migrations.AlterField(
            model_name='historicalcardmodel',
            name='owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用途分类'),
        ),
    ]
