---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devman-mysql-bak
  labels:
    app.kubernetes.io/component: paas
    app.kubernetes.io/name: devman-mysql-bak
  namespace: devman
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: devman-mysql-bak
  labels:
    app.kubernetes.io/component: paas
    app.kubernetes.io/name: devman-mysql-bak
  namespace: devman
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: harbor.uat.enflame.cc/library/mysql:5.7
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - mysqldump -u $MYSQL_USER -p"$MYSQL_PASSWORD" -h devman-mysql mvtest > /var/lib/mysql/backup/`date +%Y%m%d%H`.sql
            volumeMounts:
              - name: devman-mysql-bak
                mountPath: /var/lib/mysql/backup
            env:
              - name: MYSQL_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: devman-mysql
                    key: MYSQL_DATABASE
              - name: MYSQL_USER
                valueFrom:
                  configMapKeyRef:
                    name: devman-mysql
                    key: MYSQL_USER
              - name: MYSQL_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: devman-mysql
                    key: MYSQL_PASSWORD
          restartPolicy: Never
          volumes:
            - name: devman-mysql-bak
              persistentVolumeClaim:
                claimName: devman-mysql-bak
                readOnly: false