---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devman-mysql-pvc
  labels:
    app.kubernetes.io/component: paas
    app.kubernetes.io/name: devman-mysql-pvc
  namespace: devman
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi