---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: paas
    app.kubernetes.io/name: devman-mysql-svc
  name: devman-mysql-svc
  namespace: devman
spec:
  selector:
    app.kubernetes.io/component: paas
    app.kubernetes.io/name: devman-mysql-svc
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql