# Generated by Django 3.2.6 on 2021-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='user',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='users.deviceuser', verbose_name='申请者'),
        ),
        migrations.AddField(
            model_name='materialsmodel',
            name='users',
            field=models.ManyToManyField(blank=True, max_length=20, to='users.DeviceUser', verbose_name='使用者'),
        ),
    ]
