# Generated by Django 3.2.6 on 2021-11-16 13:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('dept', models.CharField(default='CSE', max_length=10, verbose_name='预算部门')),
                ('source', models.CharField(max_length=20, verbose_name='数据源头')),
                ('status', models.CharField(blank=True, choices=[('0', '未发生'), ('1', '已发生')], default='0', max_length=5, null=True, verbose_name='状态')),
                ('project', models.CharField(max_length=20, verbose_name='项目')),
                ('budget_body', models.ImageField(default=1, upload_to='', verbose_name='采购主体')),
                ('budget_num', models.CharField(help_text='采购申请所需', max_length=20, verbose_name='预算编号')),
                ('type_one', models.CharField(max_length=30, verbose_name='类别-1')),
                ('type_two', models.CharField(max_length=100, verbose_name='类别-2')),
                ('description', models.CharField(max_length=50, verbose_name='内容描述')),
                ('user_dept', models.CharField(default='CSE', max_length=5, verbose_name='使用部门')),
                ('start_time', models.CharField(max_length=10, verbose_name='预计采购时间')),
                ('end_time', models.CharField(max_length=10, verbose_name='预计到货时间')),
                ('currency', models.CharField(default='RMB', max_length=5, verbose_name='预算币种')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('price', models.FloatField(verbose_name='不含税总价')),
                ('tax', models.FloatField(verbose_name='税额')),
                ('total', models.FloatField(verbose_name='含税总价')),
            ],
            options={
                'verbose_name': '预算汇总',
                'verbose_name_plural': '预算汇总',
            },
        ),
    ]
