# Generated by Django 3.2.6 on 2021-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('materials', '0003_budgetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsmodel',
            name='users',
            field=models.ManyToManyField(blank=True, max_length=20, null=True, to='users.DeviceUser', verbose_name='使用者'),
        ),
    ]
