# Generated by Django 3.2.6 on 2021-11-21 13:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_materialsmodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialsmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='materialsmodel',
            name='users',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='user',
            field=models.CharField(max_length=20, verbose_name='申请者'),
        ),
    ]
