# Generated by Django 3.2.6 on 2021-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20211121_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetmodel',
            name='year',
            field=models.CharField(default=2021, max_length=10, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='budgetmodel',
            name='budget_num',
            field=models.CharField(help_text='采购申请所需', max_length=20, unique=True, verbose_name='预算编号'),
        ),
    ]
