# Generated by Django 3.2.6 on 2021-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20211121_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmodel',
            name='budget_body',
            field=models.IntegerField(default=1, verbose_name='采购主体'),
        ),
    ]
