# Generated by Django 3.2.6 on 2021-11-07 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('title', models.CharField(max_length=50, verbose_name='需求主题')),
                ('request', models.TextField(verbose_name='需求详情')),
                ('result', models.BooleanField(default=False, verbose_name='处理结果')),
                ('handler', models.CharField(default='cse', max_length=20, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '机房需求',
                'verbose_name_plural': '机房需求',
            },
        ),
    ]
