# Generated by Django 3.2.6 on 2021-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('labsmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.deviceuser', verbose_name='提交者'),
        ),
    ]
