# Generated by Django 3.2.6 on 2021-11-16 13:02

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('labsmanage', '0002_labrequests_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabcloudModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('customer', models.JSONField(default={'company': '', 'contact': '', 'email': '', 'industry': '', 'locate': '', 'name': '', 'phone': '', 'position': '', 'use': ''}, help_text='customer info', verbose_name='客户信息')),
                ('bussiness', models.CharField(max_length=20, verbose_name='商务负责人')),
                ('status', models.CharField(blank=True, choices=[('0', '使用中'), ('1', '已完成')], default='0', max_length=5, null=True, verbose_name='状态')),
                ('card_type', models.CharField(choices=[('0', '训练'), ('1', '推理')], default='0', max_length=5, verbose_name='卡类型')),
                ('use_time', models.DateTimeField(verbose_name='申请时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('use_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='使用天数')),
                ('software', models.CharField(max_length=40, verbose_name='软件版本')),
                ('device', models.CharField(max_length=50, verbose_name='设备名称')),
                ('login', models.JSONField(default={'port': '32222,32333', 'pwd': 'passwd', 'ssh': 'ssh root@58.247.94.54 -p 32222', 'user': 'root'}, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='login info ssh,port,user,pwd', verbose_name='登录信息')),
                ('owner', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='users.deviceuser', verbose_name='CSE负责人')),
            ],
            options={
                'verbose_name': '远测使用',
                'verbose_name_plural': '远测使用',
            },
        ),
    ]
