# Generated by Django 3.2.6 on 2021-11-16 13:06

import django.core.serializers.json
from django.db import migrations, models
import labsmanage.models


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0003_labcloudmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcloudmodel',
            name='customer',
            field=models.JSONField(default=labsmanage.models.customer_info, help_text='customer info', verbose_name='客户信息'),
        ),
        migrations.AlterField(
            model_name='labcloudmodel',
            name='login',
            field=models.JSONField(default=labsmanage.models.login_info, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='login info ssh,port,user,pwd', verbose_name='登录信息'),
        ),
    ]
