# Generated by Django 3.2.6 on 2021-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0004_auto_20211116_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcloudmodel',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
    ]
