# Generated by Django 3.2.6 on 2021-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0005_alter_labcloudmodel_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcloudmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
