# Generated by Django 3.2.6 on 2021-12-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_deviceborrow_is_return'),
        ('labsmanage', '0006_alter_labcloudmodel_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequests',
            name='borrowed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.deviceborrow', verbose_name='设备借用'),
        ),
    ]
