# Generated by Django 3.2.6 on 2022-04-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0007_labrequests_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcloudmodel',
            name='name',
            field=models.CharField(default='Enflame', max_length=50, verbose_name='客户名称'),
        ),
    ]
