# Generated by Django 3.2.6 on 2023-01-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0008_labcloudmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequests',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='需求分类'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='static/uploads/labrequests/%Y-%d-%d/', verbose_name='附件')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='labsmanage.labrequests')),
            ],
            options={
                'verbose_name': '附件信息',
                'verbose_name_plural': '附件信息',
            },
        ),
    ]
