# Generated by Django 3.2.6 on 2023-01-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0009_auto_20230112_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='labsmanage.labrequests', verbose_name='Lab需求'),
        ),
    ]
