# Generated by Django 3.2.6 on 2023-01-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0010_alter_attachment_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['id'], 'verbose_name': '附件信息', 'verbose_name_plural': '附件信息'},
        ),
    ]
