# Generated by Django 3.2.6 on 2023-01-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0011_alter_attachment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labrequests',
            old_name='type',
            new_name='req_type',
        ),
    ]
