# Generated by Django 3.2.6 on 2023-01-17 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labsmanage', '0013_rename_req_type_labrequests_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('url', models.CharField(max_length=20, unique=True, verbose_name='地址信息')),
                ('account', models.CharField(max_length=10, verbose_name='账号信息')),
                ('passwd', models.CharField(max_length=20, verbose_name='密码信息')),
                ('is_https', models.BooleanField(default=False, verbose_name='https')),
            ],
            options={
                'verbose_name': '账号信息',
                'verbose_name_plural': '账号信息',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='labrequests',
            options={'ordering': ['-date_created'], 'verbose_name': '机房需求', 'verbose_name_plural': '机房需求'},
        ),
        migrations.AddField(
            model_name='labrequests',
            name='req_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='需求时间'),
        ),
    ]
