# Generated by Django 3.2.6 on 2021-11-07 14:04

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('header_icon', models.ImageField(default='static/images/headers/default.jpg', upload_to='static/images/headers/', verbose_name='用户头像')),
                ('user_type', models.CharField(choices=[('0', '设备管理员'), ('1', '使用者')], max_length=10, verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '平台用户',
                'verbose_name_plural': '平台用户',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
