# Generated by Django 3.2.6 on 2022-04-06 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('summery', models.CharField(max_length=50, verbose_name='简述')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('is_done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.deviceuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '工作记录',
                'verbose_name_plural': '工作记录',
            },
        ),
    ]
