# Generated by Django 3.2.6 on 2021-11-17 14:41

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugCommentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherQuestionsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('date_support', models.DateTimeField(verbose_name='日期')),
                ('customer', models.CharField(max_length=50, verbose_name='客户名称')),
                ('location', models.CharField(max_length=20, verbose_name='地点')),
                ('project', models.CharField(max_length=10, verbose_name='项目')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('owner', models.CharField(max_length=20, verbose_name='支持代表')),
                ('day_counts', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='天数')),
            ],
            options={
                'verbose_name': '线下支持',
                'verbose_name_plural': '线下支持',
            },
        ),
        migrations.CreateModel(
            name='UaxTModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('type', models.CharField(blank=True, choices=[('0', 'UAT'), ('1', 'UXT')], default='0', max_length=5, null=True, verbose_name='类别')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细描述')),
                ('user', models.CharField(max_length=20, verbose_name='创建者')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('image', models.ImageField(upload_to='static/images/questions/%Y/%m/%d', verbose_name='图片')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
