# Generated by Django 3.2.6 on 2021-11-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uaxtmodel',
            options={'verbose_name': 'UAXT信息', 'verbose_name_plural': 'UAXT信息'},
        ),
    ]
