# Generated by Django 3.2.6 on 2021-11-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_uaxtmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uaxtmodel',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='uaxtmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='uaxtmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='uaxtmodel',
            name='version',
        ),
    ]
