# Generated by Django 3.2.6 on 2021-11-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20211119_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uaxtmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='uaxtmodel',
            name='detail',
            field=models.TextField(null=True, verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='uaxtmodel',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='uaxtmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'UAT'), ('1', 'UXT')], default='0', max_length=5, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='uaxtmodel',
            name='version',
            field=models.CharField(max_length=50, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='uaxtmodel',
            name='user',
            field=models.CharField(max_length=20, null=True, verbose_name='创建者'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/questions/%Y-%m-%d-%H-%M-%S/', verbose_name='图片')),
                ('uaxt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='questions.uaxtmodel')),
            ],
            options={
                'verbose_name': '附件信息',
                'verbose_name_plural': '附件信息',
            },
        ),
    ]
