# Generated by Django 3.2.6 on 2021-11-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20211122_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attach',
            field=models.FileField(null=True, upload_to='static/images/questions/%Y-%d-%d/', verbose_name='附件'),
        ),
    ]
