# Generated by Django 3.2.6 on 2021-11-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_attachment_attach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name': '问题信息', 'verbose_name_plural': '问题信息'},
        ),
    ]
