# Generated by Django 3.2.6 on 2021-12-18 14:23

import django.core.serializers.json
from django.db import migrations, models
import sampletest.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('customer', models.CharField(max_length=100, verbose_name='客户名称')),
                ('info', models.JSONField(default=sampletest.models.default_info, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='info for sample test', verbose_name='送测信息')),
                ('user', models.CharField(max_length=20, verbose_name='处理人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
