# Generated by Django 3.2.6 on 2021-12-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampletest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampletestmodel',
            options={'verbose_name': '送样测试', 'verbose_name_plural': '送样测试'},
        ),
    ]
