# Generated by Django 3.2.6 on 2021-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('0', '服务器'), ('1', '工作站')], max_length=20, verbose_name='设备类型')),
                ('sn', models.CharField(max_length=100, verbose_name='序列号')),
                ('number', models.CharField(max_length=50, verbose_name='财编号')),
                ('hostname', models.CharField(max_length=60, verbose_name='主机名')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('account', models.CharField(max_length=100, verbose_name='账户')),
                ('bmc', models.CharField(blank=True, max_length=20, null=True, verbose_name='BMC地址')),
                ('bmc_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='BMC账户')),
                ('status', models.CharField(blank=True, choices=[('1', '可借'), ('2', '借出')], default='1', max_length=5, null=True, verbose_name='设备状态')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='DeviceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('lab_loc', models.CharField(max_length=10, null=True, verbose_name='Lab位置')),
                ('rack_num', models.CharField(max_length=20, null=True, verbose_name='机柜编号')),
                ('u_num', models.CharField(max_length=20, null=True, verbose_name='机柜U位')),
            ],
            options={
                'verbose_name': '设备位置',
                'verbose_name_plural': '设备位置',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('vender', models.CharField(max_length=100, null=True, unique=True, verbose_name='厂商')),
                ('cpu', models.CharField(max_length=20, verbose_name='CPU配置')),
                ('memory', models.CharField(max_length=100, verbose_name='内存配置')),
                ('mainboard', models.CharField(max_length=100, null=True, verbose_name='主板配置')),
                ('harddisk', models.TextField(verbose_name='硬盘配置')),
                ('power', models.CharField(max_length=100, null=True, verbose_name='电源配置')),
                ('network', models.CharField(max_length=100, null=True, verbose_name='网卡配置')),
            ],
            options={
                'verbose_name': '配置信息',
                'verbose_name_plural': '配置信息',
            },
        ),
        migrations.CreateModel(
            name='DeviceBorrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='编号')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('reason', models.TextField(verbose_name='借用理由')),
                ('time_borrowed', models.DateTimeField(auto_now_add=True, verbose_name='借用时间')),
                ('time_end', models.DateTimeField(auto_now=True, verbose_name='归还时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='借用的设备')),
            ],
            options={
                'verbose_name': '设备借用',
                'verbose_name_plural': '设备借用',
            },
        ),
    ]
