# Generated by Django 3.2.6 on 2021-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceborrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.deviceuser', verbose_name='使用者'),
        ),
        migrations.AddField(
            model_name='device',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.deviceconfig', verbose_name='设备配置'),
        ),
        migrations.AddField(
            model_name='device',
            name='locate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicearea', verbose_name='存放位置'),
        ),
    ]
