# Generated by Django 3.2.6 on 2021-11-16 13:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='osconfig',
            field=models.JSONField(default={'kernel': '', 'os_name': ''}, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='系统配置'),
        ),
    ]
