# Generated by Django 3.2.6 on 2021-11-16 13:06

import devices.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_deviceconfig_osconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='osconfig',
            field=models.JSONField(default=devices.models.os_config, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='系统配置'),
        ),
    ]
