# Generated by Django 3.2.6 on 2021-11-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_deviceconfig_osconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_cse',
            field=models.BooleanField(default=True, verbose_name='是否CSE'),
        ),
    ]
