# Generated by Django 3.2.6 on 2021-11-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_is_cse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备信息', 'verbose_name_plural': '设备信息'},
        ),
    ]
