# Generated by Django 3.2.6 on 2021-11-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceborrow',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.device', verbose_name='借用的设备'),
        ),
    ]
