# Generated by Django 3.2.6 on 2021-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_deviceborrow_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='memory',
            field=models.CharField(max_length=50, verbose_name='内存配置'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='network',
            field=models.CharField(max_length=50, null=True, verbose_name='网卡配置'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='power',
            field=models.CharField(max_length=50, null=True, verbose_name='电源配置'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='vender',
            field=models.CharField(max_length=20, null=True, verbose_name='厂商'),
        ),
    ]
