# Generated by Django 3.2.6 on 2021-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20211120_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='model',
            field=models.CharField(max_length=100, null=True, verbose_name='型号'),
        ),
    ]
