# Generated by Django 3.2.6 on 2021-11-20 14:20

import devices.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_deviceconfig_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicearea',
            name='lab_loc',
        ),
        migrations.RemoveField(
            model_name='devicearea',
            name='rack_num',
        ),
        migrations.RemoveField(
            model_name='devicearea',
            name='u_num',
        ),
        migrations.AddField(
            model_name='devicearea',
            name='location',
            field=models.JSONField(default=devices.models.area_temp, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='设备位置'),
        ),
    ]
