# Generated by Django 3.2.6 on 2021-11-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_auto_20211120_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicearea',
            options={'verbose_name': '位置信息', 'verbose_name_plural': '位置信息'},
        ),
        migrations.AddField(
            model_name='devicearea',
            name='info',
            field=models.CharField(max_length=20, null=True, verbose_name='提示信息'),
        ),
    ]
