# Generated by Django 3.2.6 on 2021-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_auto_20211120_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceborrow',
            name='time_borrowed',
            field=models.DateTimeField(verbose_name='借用时间'),
        ),
        migrations.AlterField(
            model_name='deviceborrow',
            name='time_end',
            field=models.DateTimeField(verbose_name='归还时间'),
        ),
    ]
