# Generated by Django 3.2.6 on 2021-12-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0016_auto_20211120_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='编号')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='添加时间')),
                ('date_updated', models.DateTimeField(blank=True, editable=False, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('0', '服务器'), ('1', '工作站')], max_length=20, verbose_name='设备类型')),
                ('sn', models.CharField(max_length=100, verbose_name='序列号')),
                ('number', models.CharField(max_length=50, verbose_name='财编号')),
                ('hostname', models.CharField(max_length=60, verbose_name='主机名')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('account', models.CharField(max_length=100, verbose_name='账户')),
                ('bmc', models.CharField(blank=True, max_length=20, null=True, verbose_name='BMC地址')),
                ('bmc_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='BMC账户')),
                ('is_cse', models.BooleanField(default=True, verbose_name='是否CSE')),
                ('status', models.CharField(blank=True, choices=[('1', '可借'), ('2', '借出')], default='1', max_length=5, null=True, verbose_name='设备状态')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('config', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.deviceconfig', verbose_name='设备配置')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.devicearea', verbose_name='存放位置')),
            ],
            options={
                'verbose_name': 'historical 设备信息',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
