# Generated by Django 3.2.6 on 2021-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_historicaldevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicearea',
            name='info',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='提示信息'),
        ),
        migrations.AlterField(
            model_name='deviceborrow',
            name='time_borrowed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='借用时间'),
        ),
        migrations.AlterField(
            model_name='deviceborrow',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='mainboard',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主板配置'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='网卡配置'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电源配置'),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='vender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='厂商'),
        ),
    ]
