# Generated by Django 3.2.6 on 2021-12-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_auto_20211209_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceborrow',
            name='time_borrowed',
            field=models.DateTimeField(null=True, verbose_name='借用时间'),
        ),
    ]
