# Generated by Django 3.2.6 on 2021-12-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_deviceborrow_time_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceborrow',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='是否归还'),
        ),
    ]
