# Generated by Django 3.2.6 on 2022-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_deviceborrow_is_return'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceborrow',
            options={'ordering': ['-time_borrowed'], 'verbose_name': '设备借用', 'verbose_name_plural': '设备借用'},
        ),
        migrations.AddField(
            model_name='device',
            name='vender_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='vender_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='型号'),
        ),
    ]
