# Generated by Django 3.2.6 on 2022-08-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_auto_20220410_1423'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deviceborrow',
            index=models.Index(fields=['time_borrowed'], name='devices_dev_time_bo_e816da_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceborrow',
            index=models.Index(fields=['date_created'], name='devices_dev_date_cr_0a4479_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceborrow',
            index=models.Index(fields=['date_updated'], name='devices_dev_date_up_31af01_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceborrow',
            index=models.Index(fields=['is_return'], name='devices_dev_is_retu_567d15_idx'),
        ),
    ]
