# Generated by Django 3.2.6 on 2023-01-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20220823_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vender_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用途分类'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='vender_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用途分类'),
        ),
    ]
