# Generated by Django 3.2.6 on 2023-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_auto_20230109_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='pcie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='pcie信息'),
        ),
    ]
