# Generated by Django 3.2.6 on 2023-01-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_deviceconfig_pcie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='pcie',
            field=models.CharField(default='Gen3', max_length=20, verbose_name='pcie信息'),
        ),
    ]
